name: Build packer vm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create (or update) empty release for this tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          make_latest: true
          generate_release_notes: true
          fail_on_unmatched_files: false
          prerelease: false

  packer:
    needs: prepare_release
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            name: practice-vm
          - runner: ubuntu-24.04
            name: practice-vm-arm
    runs-on: ${{ matrix.runner }}
    name: Run Packer on ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install VirtualBox and Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y virtualbox virtualbox-guest-additions-iso

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        working-directory: ./.github/build-image
        id: init
        run: PACKER_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} packer init .

      - name: Run `packer validate`
        working-directory: ./.github/build-image
        id: validate
        run: packer validate .

      - name: Build packer image
        working-directory: ./.github/build-image
        run: |
          packer build -only=virtualbox-iso.${{ matrix.name }} .

      - name: Split the vm file into 2G chunks
        working-directory: ./.github/build-image/build
        run: |
          zip -s 1900m -r -0 ${{ matrix.name }}.zip ${{ matrix.name }}.ova

      - name: Upload assets to the existing release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare_release.outputs.tag }}
          fail_on_unmatched_files: false
          files: |
            .github/build-image/build/${{ matrix.name }}.z*
